### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by btwise** [ic005k/PlistEDPlus#1]
可以把纯plist编辑器集成在你的OCC里，传递GUI编辑选项等参数，随时切换为plist编辑模式，不是更好？

**Comment by ic005k** [comment]
是的，这样会更理想。但为了跨平台，我选择的开发工具是Qt，而不是xcode。如果是采用xcode来写qtocc的话，集成plist的编辑环境非常容易（xcode自带），所以如果要把plist的编辑环境集成到qtocc里面，时间成本是比较高的。
感谢建议，有你们的参与，会越来越好！

**Comment by btwise** [comment]
> 是的，这样会更理想。但为了跨平台，我选择的开发工具是Qt，而不是xcode。如果是采用xcode来写qtocc的话，集成plist的编辑环境非常容易（xcode自带），所以如果要把plist的编辑环境集成到qtocc里面，时间成本是比较高的。
> 感谢建议，有你们的参与，会越来越好！

可以简化处理，把PLIST编辑作为一个整体放入OCC，OCC只传递临时文件名参数到PLIST编辑器就可以了，没必要所有的选项都做处理！

**Comment by ic005k** [comment]
这个主意不错，回头有时间我琢磨一下
但是在occ里面再编辑plist，实际意义何在

**Comment by btwise** [comment]
> 这个主意不错，回头有时间我琢磨一下
> 但是在occ里面再编辑plist，实际意义何在

意义在于，一些人喜欢这种模式的编辑模式，但有的地方需要GUI模式，我在OCC里把这个功能叫做“高手模式”

**Comment by btwise** [comment]
对于plist编辑器来说，目前缺少更改条目顺序，和拖拽条目改变顺序等基本功能，右键扩展菜单应该更为丰富，比如添加同级项，添加子项等等，可参考plisteditpro和ProperTree来进行完善！

**Comment by ic005k** [comment]
好的，在后续的版本里面，我会逐一来完善这些功能。

**Comment by btwise** [comment]
@ic005k 
条目移动无法实现移动
折叠展开的图标建议使用更小的箭头图标替代，目前图标太大，影响美观

**Comment by ic005k** [comment]
> @ic005k
> 条目移动无法实现移动
> 折叠展开的图标建议使用更小的箭头图标替代，目前图标太大，影响美观

1.条目的移动只能同级进行，不能跨级，而且数组之内的条目，不允许移动。如果跨级就属于剪切和粘贴的范畴了，不过，这是一个低频次的动作。
2.折叠和展开的图标大小，我有通过代码来控制，在win下是正常的，但mac下貌似不起作用，一直是占满整个行高，回头我再分析一下原因，解决它。
感谢反馈！

**Comment by btwise** [comment]
> > @ ic005k重力
> > 移动无法实现移动
> > 折叠展开的图标建议使用更小的箭头图标替代，当前图标太大，影响美观
> 
> 1。小型的移动只能同级进行，不能跨级，而且层叠之内的压缩，可以移动。如果跨级就属于剪切和粘贴的局部了，不过，这是一个替换次的动作
> 。2 。折叠和展开的图标大小，我有通过代码来控制，在赢下是正常的，但MAC下貌似不起作用，一直是占满整个行高，回头我再分析一下原因，解决它。
> 感谢反馈！

1、我说的不能移动是指，如果上级数据类型是array的话，本机dict类型的条目无法移动，其他类型可以移动
![image](https://user-images.githubusercontent.com/38809560/97142069-efc50100-179a-11eb-8141-4200d7358ba1.png)
2、展开收缩的image选项去掉，使用treeview空间自带的小箭头即可，几乎所有的树形编辑器都是这样的
3、右键菜单增加把同级项变为子项，或把子项变为同级项的功能呢
4、默认新建的根字符串用`root`替代`plist`舒服一些，本地化文件里加入翻译为`根`的内容
5、布尔类型的数值选择true或false操作逻辑并不舒服，改为列表选择形式，同时加入本地化翻译，包括其他数据类型的显示；如果只针对OC编辑，建议去掉单精度(real)数据类型
![image](https://user-images.githubusercontent.com/38809560/97142492-a88b4000-179b-11eb-90fc-58b86be36e10.png)
![image](https://user-images.githubusercontent.com/38809560/97142507-b2ad3e80-179b-11eb-8bc5-661f75385c76.png)

**Comment by btwise** [comment]
@ic005k 
在每一父级项后面，应该计算子项的数量信息，在编辑OC的时候一目了然，可以判断是否缺少条目！
![image](https://user-images.githubusercontent.com/38809560/97143922-89da7880-179e-11eb-88e9-20d512998376.png)

**Comment by btwise** [comment]
@ic005k 
添加退出时检查当前文件是否未保存的判断！

**Comment by ic005k** [comment]
好的，后面会逐一完善，感谢建议

**Comment by btwise** [comment]
> 好的，后面会逐一完善，感谢建议

我提的这些基本都是刚性需求，完善这些，其他功能和细节可以慢慢润色

**Comment by ic005k** [comment]
大致的框架，基本上已完成。关于节点图标，我在新版里面增加了偏好设置，可以选择系统默认的节点图标，请下载最新的版本。
感谢关注和建议。

**Comment by btwise** [comment]
> 大致的框架，基本上已完成。关于例程图标，我在新版里面增加了替代设置，可以选择系统替换的例程图标，请下载最新的版本。
> 感谢关注和建议。

`array`下级的`dict`条目还是无法移动顺序！！

**Comment by btwise** [comment]
> > 大致的框架，基本上已完成。关于例程图标，我在新版里面增加了替代设置，可以选择系统替换的例程图标，请下载最新的版本。
> > 感谢关注和建议。
> 
> `array`下级的`dict`条目还是无法移动顺序！！

新版本已经可以更改条目顺序了，期待使用鼠标拖动功能！

**Comment by ic005k** [comment]
> > > 大致的框架，基本上已完成。关于例程图标，我在新版里面增加了替代设置，可以选择系统替换的例程图标，请下载最新的版本。
> > > 感谢关注和建议。
> > 
> > 
> > `array`下级的`dict`条目还是无法移动顺序！！
> 
> 新版本已经可以更改条目顺序了，期待使用鼠标拖动功能！

好的，已记录。回头完成一些局部优化和首轮白盒测试之后，再来完善这些锦上添花的功能，感谢反馈。

**Comment by btwise** [comment]
> > > > 大致的框架，基本上已完成。关于例程图标，我在新版里面增加了替代设置，可以选择系统替换的例程图标，请下载最新的版本。
> > > > 感谢关注和建议。
> > > 
> > > 
> > > `array`下级的`dict`条目还是无法移动顺序！！
> > 
> > 
> > 新版本已经可以更改条目顺序了，期待使用鼠标拖动功能！
> 
> 好的，已记录。回头完成一些局部优化和首轮白盒测试之后，再来完善这些锦上添花的功能，感谢反馈。

啥叫白盒测试

**Comment by ic005k** [comment]
> > > > > 大致的框架，基本上已完成。关于例程图标，我在新版里面增加了替代设置，可以选择系统替换的例程图标，请下载最新的版本。
> > > > > 感谢关注和建议。
> > > > 
> > > > 
> > > > `array`下级的`dict`条目还是无法移动顺序！！
> > > 
> > > 
> > > 新版本已经可以更改条目顺序了，期待使用鼠标拖动功能！
> > 
> > 
> > 好的，已记录。回头完成一些局部优化和首轮白盒测试之后，再来完善这些锦上添花的功能，感谢反馈。
> 
> 啥叫白盒测试

简单地讲，就是阅读所有写的源代码，分析各个源代码模块之间的关联性，以及这些关联性会不会导致软件出现一些潜在的bug等等。通俗地说，就是重新再梳理一下源代码，看看有没有逻辑上的问题。这是软件质量控制过程中，非常重要的环节。
