### ISSUE TITLE
CMD+Q does not exit from the app

### ISSUE THREAD

**Issue by 1alessandro1** [ic005k/PlistEDPlus#10]
Hi, thanks for the icons redesign, it looks way better than before!

However it seems like the Quit option is gone in release V1.0.44 (macOS Big Sur), could you double check on your side?

Thank you

**Comment by ic005k** [comment]
Ok, I'll double check it, thanks for the feedback.

**Comment by 1alessandro1** [comment]
Edit: I noticed that the shortcuts are CMD+W to close a single tab and Opt+CMD+W to close all tabs, could you add CMD+Q to close everything without asking "hibernating the session, as in VSCode" and when you reopen the app the configs are opened as they were previously?

**Comment by ic005k** [comment]
Ok, CMD+Q is actually there, it has been working fine on my side, maybe I need to test it on other machines, anyway, I will fix the issue.

**Comment by ic005k** [comment]
Please download a beta version here and see if CMD+Q works?

https://github.com/ic005k/PlistEDPlus/suites/2439513334/artifacts/52204192

**Comment by 1alessandro1** [comment]
Thank you, now it works ^^

Before:
![Screenshot 2021-04-07 at 16 19 06](https://user-images.githubusercontent.com/46293832/113882056-465c4f80-97bd-11eb-9ddb-a57dbfeb82c4.png)

After:
![Screenshot 2021-04-07 at 16 20 42](https://user-images.githubusercontent.com/46293832/113882087-4d835d80-97bd-11eb-9f67-5fc5f955b463.png)
