### ISSUE TITLE
<true/> became <true />,<false/> became <false /> Is this acceptable as XML? 

### ISSUE THREAD

**Issue by mifjpn** [ic005k/PlistEDPlus#11]
Thank you for the wonderful application.
Many XMLs use &lt;true/&gt;, &lt;false/&gt;, but when I edit with this PlistEDPlus, all of them are replaced with &lt;true /&gt;, &lt;false /&gt;.
Wouldn&#x27;t it be better not to replace it for greater availability in most XML?
Thank you.

**Comment by ic005k** [comment]
I think it's just a matter of style, ease of reading, nothing more. Thanks for the feedback.

**Comment by mifjpn** [comment]
When we look at the following
<a href="https://www.w3.org/TR/xml/">https://www.w3.org/TR/xml/</a>
It seems to be arbitrary in XML whether to put a space before /&gt;, but in W3C, as follows
<a href="https://www.w3.org/TR/xhtml1/#guidelines">https://www.w3.org/TR/xhtml1/#guidelines</a>
It seems that it is supposed to put a space.
So you say this space is a cosmetic issue, isn&#x27;t it?
I can understand.
Thank you.

**Comment by mifjpn** [comment]
I looked it up.
There are no spaces in BBedit, PlisEdit Pro or Sublime Text.
It's not just a cosmetic issue.
In order for more people to use this application, I think it's better to have no space.
I think it is necessary for your program to be used by everyone, so I suggest it.
Thank you.

**Comment by ic005k** [comment]
Ok, I will remove this space in the next release. Thank you again for your attention.
