### ISSUE TITLE
建议更新高清图标

### ISSUE THREAD

**Issue by avialae** [ic005k/PlistEDPlus#12]
toolbar和每个键之前的三角可否更新为高清图标？
还有显示plist文本中可否调整为等宽字体？

**Comment by ic005k** [comment]
没问题，后面会不断改进的。
对了，你截图我看看图标在你那边的显示情况。

**Comment by ic005k** [comment]
我目前使用的图标大多是在这里找的：https://www.iconfinder.com/，本人不具备图标设计能力，只能找些现成的来凑合。
或者你那边有什么图标资源，都可以分享下。

**Comment by avialae** [comment]
[](url)
![capture](https://user-images.githubusercontent.com/38975492/118106316-0e75a700-b410-11eb-9948-5aa67f6d27d1.PNG)
目前用的是27寸4k显示器，200%缩放。 
你这个网站其实有很多矢量图呀，直接替换就可以啦。
加油，你这个比propertree好多了，propertree那个万年不更新的hi-dpi眼睛都要瞎了。

**Comment by ic005k** [comment]
看了你的截图，明白了。后面会改进的，欢迎任何问题或建议。

**Comment by ic005k** [comment]
你回头下个测试版看看效果如何：https://github.com/ic005k/PlistEDPlus/suites/2739480975/artifacts/60520586
这个只是目前测试使用，其图标会不断地进行优化。

**Comment by ic005k** [comment]
最新的测试版都可以在此处下载：https://github.com/ic005k/PlistEDPlus/actions

**Comment by ic005k** [comment]
已更新，请下载最新的版本。

**Comment by avialae** [comment]
有一说一，整个做的挺好的，更新速度也快，加油！
