### ISSUE TITLE
Linux bugs

### ISSUE THREAD

**Issue by 1alessandro1** [ic005k/PlistEDPlus#13]
Hi, I've tested today your app, it has improved a lot since the last time I updated it :smile: 

However, with v1.0.58 on debian 10 buster, I've encountered some bugs:

 1. a new entry is not created when clicking on + on a dictionary, for now the only way is to add a new entry manually with CRTL+C and CRTL+V or doing it from the menu. Pressing minus works when deleting a key though
 2. When adding a new entry from the `New Silbing` menu, the `data` field restriction applies to both fields, the key and the value (more explanation below) this should be corrected to be applied only to the value and not the key
 3. the new string accepts only hex input for the new e.g. `<key>device-id</key>` value, so i cannot type the "i" letter since it's not 0123456789ABCDEF from the hex values

Hope to hear from you soon :)

**Comment by ic005k** [comment]
Thanks for the feedback, I will fix these issues in the next release.

**Comment by ic005k** [comment]
Thanks for the feedback, I will fix these issues in the next release.

**Comment by ic005k** [comment]
> 1. a new entry is not created when clicking on + on a dictionary, for now the only way is to add a new entry manually with CRTL+C and CRTL+V or doing it from the menu. Pressing minus works when deleting a key though

There is a difference between creating a new child item and creating a new sibling item, and the shortcut keys for both can be found in the menu. The condition for creating a new child item is that the data type must be a dictionary or an array.

**Comment by ic005k** [comment]
> * When adding a new entry from the `New Silbing` menu, the `data` field restriction applies to both fields, the key and the value (more explanation below) this should be corrected to be applied only to the value and not the key
> * the new string accepts only hex input for the new e.g. `<key>device-id</key>` value, so i cannot type the "i" letter since it's not 0123456789ABCDEF from the hex values

This issue has been fixed and will be released later.

**Comment by 1alessandro1** [comment]
> This issue has been fixed and will be released later.

Thanks, it works now. 

> [...] creating new child item and creating a new sibling item, and the shortcut keys for both can be found in the menu. 

I would ask if you could set the `+` for [this behaviour](https://streamable.com/3miqxa), but maybe a better approach in the long term would be to add customizable shortcuts menu?
