### ISSUE TITLE
click boolean item, text window doesn't jump to the raw

### ISSUE THREAD

**Issue by cguo2013** [ic005k/PlistEDPlus#15]
it will always stay in the first boolean item. 
other type of data format don't have such problem.
confirmed in win64 V1.0.60 & V1.0.61

**Comment by ic005k** [comment]
This is a known issue, that is, if there are duplicate entries for Key, DataType, and Value, the positioning of the plist text will be fixed on the first identical entry.
I will probably redesign the algorithm for this piece later, thanks for the feedback.
