### ISSUE TITLE
能不能加个ProperTree里的 oc snapshot 的功能

### ISSUE THREAD

**Issue by k2y1982** [ic005k/PlistEDPlus#18]
如题。如果加了这个功能，就可以彻底不用ProperTree了

**Comment by ic005k** [comment]
具体是？能否描述一下。

**Comment by EMP83** [comment]
It is safe to be used with OC Config.plist and to replace ProperTree? This program can do OS Snapshot?
Thank You

**Comment by k2y1982** [comment]
比如我将自己的acpi，kext放入原版的oc里，只需要使用oc snapshot，就能自动根据我放入的文件来修改plist了。
![1](https://user-images.githubusercontent.com/5109711/145739280-b2f38068-905b-4f11-b416-b5e33d716ba1.png)
![3](https://user-images.githubusercontent.com/5109711/145739299-07bb44e6-360b-4ebf-8a8c-347ee8a6a89a.png)
![5](https://user-images.githubusercontent.com/5109711/145739309-1d8503ac-3ba1-49e8-8359-d0f369c0b369.png)
![6](https://user-images.githubusercontent.com/5109711/145739321-d4702a57-671f-4df8-8e39-1ffd7f7c3ce9.png)

**Comment by k2y1982** [comment]
这个功能会扫描 ACPI Drivers Kexts Tools目录，将plist里默认的值清空，并换为目录里实际存在的文件。

**Comment by ic005k** [comment]
这个功能的话，PlistEDPlus也有类似的，比如你只需选择ACPI->Add，这个时候拖动一个或多个alm文件到软件界面，则就会自动增加它们。
不过，PlistEDPlus的定位和其它软件可能有些不同，PlistEDPlus定位为通用型的Plist编辑器，不会对OC做过多的针对性处理。其实，这些都没什么玄机，异曲同工。
因为我还写了个OCAT是专门针对OC的，所以PlistEDPlus可能不会再做针对OC的这些事情了。

**Comment by k2y1982** [comment]
有方法添加也可以的，只是有时候plist更新，在ocat还没更新的时候，会用到PlistEDPlus，特别是win的版本，方便在pe里改数值。
