### ISSUE TITLE
Update engine did not handle redirections (same happens with QtiASL.app too)

### ISSUE THREAD

**Issue by nms42** [ic005k/PlistEDPlus#19]
Attached downloaded file (actually html body of redirection response) with fake .txt (to overcome github limitation)

[PlistEDPlus_Mac.dmg.txt](https://github.com/ic005k/PlistEDPlus/files/7669038/PlistEDPlus_Mac.dmg.txt)

**Comment by ic005k** [comment]
In a later version I may add a proxy option to break through the GitHub limitations, just like OCAT. Thanks for the suggestions and feedback.
