### ISSUE TITLE
V2022

### ISSUE THREAD

**Issue by luckman212** [ic005k/PlistEDPlus#20]
Thank you for PlistEdPlus!

One small thing:  can you please go back to semantic version numbering?

Latest version GitHub tag == `1.0.94` but version of app's info.plist  == `PlistEDPlus - V2022` 
see https://github.com/ic005k/PlistEDPlus/commit/9cfa850fd5c20b5e55c1216728b70d58b41d6880#diff-80650d12c6dd3934a12d0a6121646c6d338b5897b44f9d2b95639ada56c32c17

This breaks things like MacUpdater as well as my custom autoupdate script

**Comment by ic005k** [comment]
The next version will go back to the previous state, thanks for the feedback.
