### ISSUE TITLE
关于调整系统界面 上下两部分的比例问题。

### ISSUE THREAD

**Issue by iaihc** [ic005k/PlistEDPlus#21]
开发人员你好！
    使用用户，我对于你开发的软件表示感谢，很好用，现在比较麻烦的是每次打开这个软件，如果能自定义下打开后的上面和下面显示部分的比例就好，保留上次调整的上下比例才好。

**Comment by ic005k** [comment]
你好，没太明白你说的意思。
是指plist文本窗口的比例？
还是你不喜欢显示这个plist文本窗口?

**Comment by ic005k** [comment]
如果你不想显示plist文本，在偏好设置里面可以关闭它。
plist文本的显示高度，默认是按最小高度显示的，每次打开都是按最小高度。

**Comment by iaihc** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ic005k/PlistEDPlus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月22日(星期三) 中午11:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ic005k/PlistEDPlus] 关于调整系统界面 上下两部分的比例问题。 (Issue #21)





 
你好，没太明白你说的意思。
 是指plist文本窗口的比例？
 还是你不喜欢显示这个plist文本窗口?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;







如图，就是中间这条上下比例，希望能记住上次调整的位置&nbsp;

**Comment by ic005k** [comment]
该功能已添加，欢迎更多的问题或建议。
