### ISSUE TITLE
自动升级无法进行

### ISSUE THREAD

**Issue by BrushXue** [ic005k/PlistEDPlus#22]
每次打开都会问要不要自动升级，然后永远卡死在这里
![Screen Shot 2021-12-27 at 9 39 52 AM](https://user-images.githubusercontent.com/12702149/147482079-e79f7c7b-33ea-4845-b9a3-afbbc366836f.png)

**Comment by ic005k** [comment]
很简单，在“帮助”菜单中选择合适的镜像服务器，之后再选择“下载升级包”进行升级，你看哪个镜像服务快，就用哪个。
一般在5~10即可完成升级。

**Comment by ic005k** [comment]
每个镜像服务器，都可以通过“下载升级包”来测试，选个最快的就可以了。

**Comment by ic005k** [comment]
看截图，你用的是英文系统，所以默认的是GitHub直连，如果在国内肯定是不行的。

**Comment by BrushXue** [comment]
我在墙外，github直连确实不行

**Comment by BrushXue** [comment]
唯一一个下载成功的是gh.api.99988866.xyz

**Comment by ic005k** [comment]
嗯，这可能是个比较难以解决的问题。有任何问题或建议，请随时留言。

**Comment by BrushXue** [comment]
很不合理，墙外为什么GitHub直连反而不行呢

**Comment by ic005k** [comment]
这个我也不清楚，据目前用户的反馈，英美用户直连都是没问题的。
大部分欧洲用户直连也是没问题的，但是德国部分用户能直连，又有个别用户不能直连。
程序代码都是一样的，但用户的实际情况表现不同，所以才加了个镜像服务器的选择，否则我真不愿意多此一举，为这个浪费时间。
总之，能连就行了，具体原因，由于用户没法提供详尽的数据，我也不好分析，也懒得去分析。

**Comment by ic005k** [comment]
还有个别日本用户也是不能直连，也只能走镜像，具体原因未知。

**Comment by ic005k** [comment]
还有，韩国和俄罗斯地区的用户均能直连，从未收到联网之类的反馈，因为其中有APP的贡献者分布在韩国和俄罗斯。

**Comment by ic005k** [comment]
不知道你在哪个地区，如果你愿意提供详尽的数据，我回头有空可以分析一下，尝试着做进一步的改进。

**Comment by BrushXue** [comment]
我在美东地区，需要运行什么命令？

**Comment by ic005k** [comment]
美东应该没问题的，我回头改进下APP，可以出调试信息，到时你们将调试信息给我就可以了，这是最简单的。
下一步有时间的话，我将着重改进你们这些墙外用户不能直连下载的问题，虽然很个别，但我会尝试着去分析和改进。

**Comment by ic005k** [comment]
这位用户遇到的问题和你是一样的，欧洲的。
https://github.com/ic005k/QtOpenCoreConfig/issues/102

**Comment by BrushXue** [comment]
这个应该不是我运营商的问题，前几天去另一个州的朋友家帮他倒腾黑苹果也不能直连。可

**Comment by ic005k** [comment]
好的，收到，后面你可以随时附加关于联网方面的任何信息。
请关注APP后续的升级，我将尝试着改进它们。

**Comment by ic005k** [comment]
做了个测试文件，看看能否在你那边运行。
[download.zip](https://github.com/ic005k/PlistEDPlus/files/7782748/download.zip)

**Comment by BrushXue** [comment]
已经在brew安装了qt@5还是报错，我也要在同一个目录装一个吗？
```
dyld[58970]: Library not loaded: @rpath/QtNetwork.framework/Versions/5/QtNetwork
  Referenced from: /Users/gux215/Downloads/download
  Reason: tried: '/Users/gux215/Downloads/../Frameworks/QtNetwork.framework/Versions/5/QtNetwork' (no such file), '/Users/zh/Qt/5.15.2/clang_64/lib/QtNetwork.framework/Versions/5/QtNetwork' (no such file), '/Users/gux215/Downloads/../Frameworks/QtNetwork.framework/Versions/5/QtNetwork' (no such file), '/Users/zh/Qt/5.15.2/clang_64/lib/QtNetwork.framework/Versions/5/QtNetwork' (no such file), '/Library/Frameworks/QtNetwork.framework/Versions/5/QtNetwork' (no such file), '/System/Library/Frameworks/QtNetwork.framework/Versions/5/QtNetwork' (no such file)
[1]    58970 abort      ./download
```

**Comment by ic005k** [comment]
我打了个包，你直接在终端运行包里面的download.app/Contents/MacOS/download看看？

[Uploading download.app.zip…]()

**Comment by ic005k** [comment]
我打了个包，你直接在终端运行包里面的download.app/Contents/MacOS/download看看？

https://github.com/ic005k/QtOpenCoreConfigDatabase/releases/download/1.0.0/download.app.zip

**Comment by ic005k** [comment]
如果还是不行的话，你通过OCAT的偏好设置里面的“测试”，将下载里面的日志贴过来我看看。

![test](https://user-images.githubusercontent.com/25247437/147531257-b0df2a3c-6657-4059-b726-c0dd3c9a403e.png)

**Comment by ic005k** [comment]
[downloadPro.app.zip](https://github.com/ic005k/PlistEDPlus/files/7783414/downloadPro.app.zip)

再提供一个图形化的测试工具，可直接运行。

**Comment by BrushXue** [comment]
OCAT下载完全正常
测试工具一个字节也不走
![Screen Shot 2021-12-28 at 12 53 44 PM](https://user-images.githubusercontent.com/12702149/147593619-1fbb3f8d-7427-459f-87e4-b039c38d911e.png)

**Comment by ic005k** [comment]
你再用这个测试工具下载一个美国境内的文件看看？

**Comment by ic005k** [comment]
随便一个文件都可以，只要服务器在美国境内即可。

**Comment by BrushXue** [comment]
Github的文件全部卡在“下载中”
其他网站的文件卡在“网络请求中”

**Comment by ic005k** [comment]
好的，收到，有空会继续分析，感谢配合。
