### ISSUE TITLE
Missing features

### ISSUE THREAD

**Issue by dreamwhite** [ic005k/PlistEDPlus#23]
Hi there,
thank you so much for your release. I tried updating to 1.2.08 but immediately noticed that many buttons disappeared. Below a screen of the buttons from release v1.0.93:
![image](https://user-images.githubusercontent.com/17933708/147791379-298ccc89-97d5-482a-8891-e1d3438d459c.png)

v.1.2.08:
![image](https://user-images.githubusercontent.com/17933708/147791417-3f78e4f4-d989-45f0-8880-b088c00fcdfb.png)

May I ask you what happened? 😅

**Comment by ic005k** [comment]
The user interface has been redesigned for the new version and is still being updated. Please pay attention to the subsequent upgrades of the app and thanks for the feedback.
