### ISSUE TITLE
REQUEST - Native macOS M1 Silicon version

### ISSUE THREAD

**Issue by gspannu** [ic005k/PlistEDPlus#24]
Could you please provide a macOS **M1 Silicon native** version?

Thanks...

**Comment by ic005k** [comment]
It may be provided later. Currently I don't have this compilation environment, so I can't for now.
Please pay attention to the subsequent upgrade of APP, thanks for the feedback.

**Comment by gspannu** [comment]
> It may be provided later. Currently I don't have this compilation environment, so I can't for now.
> Please pay attention to the subsequent upgrade of APP, thanks for the feedback.

You should not need any specific environments.
As long as you have Xcode running, you should be able to compile a '_universal binary_' containing both Intel & Apple Silicon versions... I believe it is just a setting in Xcode Build Options.

**Comment by ic005k** [comment]
Sorry, this app is not developed by XCode, but by Qt, so it's not as easy as you said, but Qt6 has started to support M1, so it's definitely possible in the future.
