### ISSUE TITLE
new preference to enable/disable update checking

### ISSUE THREAD

**Issue by scorpion81** [ic005k/PlistEDPlus#26]
Hello :slightly_smiling_face:  Thank you for coding this great and open source plist editor :+1:
But I found a minor annoyance.
In case you have to open PlistEDPlus quite often, close
open, and so on in order to check plist edits, you always have to dismiss
the automatic update popup message.
So I quickly added a user preference under the Help menu which should allow to optionally
turn update checking off or on.
See also PR #25

**Comment by ic005k** [comment]
Hi, I wonder if you have any ideas for designing icons, if so, can you help PlistEDPlus to design an app icon, thanks.

**Comment by ic005k** [comment]
The current app icons are what I found from the internet, not designed. If you have the ability to design icons, please use your expertise.
Thank you very much.
