### ISSUE TITLE
Can't Auto Update (Only update with safari?)

### ISSUE THREAD

**Issue by mifjpn** [ic005k/PlistEDPlus#27]
Thank you so much for making a good editor. 
When I press the button after it says there is an update, I get "Download Progress: 660.00 bytes-> 660.00 bytes", but I can't upgrade.
It seems that it will be when Safari is not the default even in Windows version and mac os version.
You have upgraded very well to improve this program, so I would like to follow up and update, 
I hope this is fixed. 
Thank you
![スクリーンショット 2022-01-14 143549](https://user-images.githubusercontent.com/7693274/149458741-17dd1aee-45cc-463c-a3c7-32dfd930aee0.jpg)
.

**Comment by mifjpn** [comment]
Thank you for your quick reply.
Where can I get to the mirror server from HELP on the menu bar?
Is the version too old?
Sorry for the basic question
![クリップボード01](https://user-images.githubusercontent.com/7693274/149484764-efab88f2-4ef7-40c5-a268-aed9e6d2dfb3.jpg)
.

**Comment by SergeySlice** [comment]
> Please select an available mirror server in the "Help" menu to update, and after you select it, click "Download upgrade package" in the help menu to see if the mirror server is available and how fast it can be downloaded.
> In short, just choose the fastest mirror server for you.

I have the same problem and I don't think I have to change server. It is fast.
The program itself has the problem.

**Comment by ic005k** [comment]
> The program itself has the problem.

The code for the automatic upgrade is here, can you please help improve these codes or see what the problem is? Thank you very much.

https://github.com/ic005k/PlistEDPlus/blob/0588420a28c9a05736bcfe5cdd800af196660155/autoupdatedialog.cpp#L183

**Comment by ic005k** [comment]
> I have the same problem and I don't think I have to change server. It is fast.

If you choose to mirror the server to work properly, I'm not going to do an in-depth analysis of this issue at this time because it's not the main function of the program, it's just a very minor secondary function and not worth the time spent on this.

**Comment by mifjpn** [comment]
Thank you for always good development.

 PlistEDPlus receives 660 bytes when updating from Git-Hub because the content is a redirect.

Starting with QT5.6, the QNetworkRequest attribute in QNetworkAccessManager.h has an additional FollowRedirectsAttribute, which can be true to resolve redirects and download the correct file.

Maybe this will eliminate the problem.

 [mifjpn](https://github.com/mifjpn) / [PlistEDPlus](https://github.com/mifjpn/PlistEDPlus)


I would be honored if I could contribute to you.

**Comment by mifjpn** [comment]
It seems to have worked and I'm happy.
It was my first time to use the development environment of qt, but it is very devised and easy to use.
Thank you very much.
