### ISSUE TITLE
/Users/shendayong/Library/Preferences下面文件会被重置吗？

### ISSUE THREAD

**Issue by shensmart** [ic005k/PlistEDPlus#29]
Hi，首先感谢作者写了这么好的软件

我发现了一个应该不算软件问题的问题

我前两天看到CrossOver试用版可以通过修改~/Library/Preferences/com.codeweavers.CrossOver.plist里面FirstRunDate值重置试用时间，就试了下，PlistEDPlus修改后保存，再打开，值已经改了，但是启动CrossOver看并不生效，我用VSCode的插件改了也保存了，但是也不生效，但是用PlistEdit Pro改了之后，能生效，不知道是这个路径下的文件有什么特殊保护措施吗？比较好奇，作者有空可以研究下看看

**Comment by ic005k** [comment]
好的，你提供下这个plist文件，我分析看看，我电脑上没装这个CrossOver

**Comment by ic005k** [comment]
这个~/Library/Preferences/目录下面的plist文件多半是二进制吧，你按二进制保存它看看？
如果是二进制，按原样保存即可，你如果按XML格式保存的话，肯定是不生效的

**Comment by ic005k** [comment]
也就是说不要在PlistEDPlus里面更改文件的保存类型，如果打开的是BIN，保存它也按默认的BIN保存，别改成XML格式

**Comment by shensmart** [comment]
> 

没改动过文件类型，保存也是成功的，重新打开也是改动后的值，但是用PlistEdit Pro打开后还是原来的没改动过的值
[com.codeweavers.CrossOver.plist.zip](https://github.com/ic005k/PlistEDPlus/files/8113577/com.codeweavers.CrossOver.plist.zip)
型

**Comment by shensmart** [comment]
这个是CrossOver的下载地址
https://www.crossoverchina.com/xiazai.html

**Comment by ic005k** [comment]
[com.codeweavers.CrossOver 2.plist.zip](https://github.com/ic005k/PlistEDPlus/files/8113732/com.codeweavers.CrossOver.2.plist.zip)

我这边改后是生效的，我改成2028了，直接打开后更改后保存，它是二进制的文件。

**Comment by ic005k** [comment]
在关闭软件的情况下替换文件

**Comment by ic005k** [comment]
它安装的win软件界面实在是接受不了，和mac风格格格不入，太老旧了，感觉

**Comment by shensmart** [comment]
> 

我这边还是不行，复制出来在其他文件夹修改了，再覆盖回去，用PlistEDPlus打开看到的是修改后的，用PlistEdit Pro打开就是没修改过的，奇怪的很，而CrossOver读取的也是没修改的那一份，可能是我自己机器的问题，忽略这个问题吧

CrossOver可以临时用用某些mac上没有的软件，资源消耗比虚拟机低很多
