### ISSUE TITLE
The plist editor crashes under certain circumstances

### ISSUE THREAD

**Issue by 1alessandro1** [ic005k/PlistEDPlus#3]
When I right click on an item/array, click on "Cut", and then ask for a new silbing for the array, the application crashes. 
Here is the log, repeated 3 times

[Archive.zip](https://github.com/ic005k/PlistEDPlus/files/5730611/Archive.zip)

**Comment by 1alessandro1** [comment]
Here's a video if you want to reproduce the issue


https://user-images.githubusercontent.com/46293832/102904061-7c293280-4471-11eb-818a-d40b7caf4c73.mov

**Comment by 1alessandro1** [comment]
Also, please consider adding shortcuts such as `+` or `-` to add or delete lines, as ProperTree has, they're handy instead of right clicking every time

**Comment by ic005k** [comment]
Thank you very much for your feedback. The above information has been received and is being processed.

**Comment by ic005k** [comment]
The problem has been solved, please download the latest version. Or download the latest version through the update check built into the app.

**Comment by ic005k** [comment]
At the same time, shortcut keys have been added. Welcome more suggestions or questions, thank you!

**Comment by 1alessandro1** [comment]
Thanks, the issue discussed in the video is solved. 

Also, only when pressing `-` the app deletes the string/line/dict etc, but nothing happens when pressing `+`

**Comment by 1alessandro1** [comment]
In particular, the only thing that happens when pressing `+` is that the `dict` opens up, but doesn't add anything to the dict itself

**Comment by ic005k** [comment]
> In particular, the only thing that happens when pressing `+` is that the `dict` opens up, but doesn't add anything to the dict itself
Please don't press any modifier keys, especially Shift key, just press the "=" key, and there are descriptions of shortcut keys in the edit menu.
