### ISSUE TITLE
[Feature request] Add support for independent windows

### ISSUE THREAD

**Issue by 1alessandro1** [ic005k/PlistEDPlus#4]
First of all, I start to say that I tried the drag and drop feature and it works perfectly, and I'm very thankful for such feature.

A couple of suggestions to push this plist editor experience *even further* (cit)

* Please add support for separate tabs, it's handy when comparing files (one on the left side of the screen, one in the other)
* The `-` (minus) button always works flawlessly when I need to delete an entry, and I saw that you implemented the `=` sign as a shortcut to add a `child`, and `CMD + =` to add a silbing, could be possible to change that to + maybe in a preference pane (I suppose that for american keyboards you need to press the shift key to use `+`, but in the IT keyboard we need to press shift to use `=`, so maybe the Plist editor can respect preferences policies to adapt to different shortcuts depending on the keyboard layout)
* While this one could be low priority, consider to improve the toolbar GUI a little, (this doesn't need to be done in a day or two, it's something that could even take a couple of weeks or more)

Thank you for your time

**Comment by ic005k** [comment]
Ok, I will improve them. Also, about the toolbar GUI, I don't have any artwork base, so I can't make these icons by myself, can you provide help or design a set of toolbar icons? Thanks!

**Comment by 1alessandro1** [comment]
Thanks for the updates, the `+` and `-` are working perfectly! 
I took some time to get how to create a new window, I suggest to add a shortcut maybe, such as `CMD+Shift+N`, that would be nice
Another cool idea would be to be able to drag a tab from a window to another, just as chrome/firefox allows (also if you drag a tab out from a group, that tab becomes independent) but these are optional, feel free to implement them whenever you want

**Comment by ic005k** [comment]
> Thanks for the updates, the `+` and `-` are working perfectly!
> I took some time to get how to create a new window, I suggest to add a shortcut maybe, such as `CMD+Shift+N`, that would be nice
> Another cool idea would be to be able to drag a tab from a window to another, just as chrome/firefox allows (also if you drag a tab out from a group, that tab becomes independent) but these are optional, feel free to implement them whenever you want

This is a great idea and I will try to implement it.
