### ISSUE TITLE
Tag text color

### ISSUE THREAD

**Issue by Drovosek01** [ic005k/PlistEDPlus#5]
Hello. Can I somehow adjust the color of the tags?

The blue color of the text in a dark theme is very difficult to read.

![image](https://user-images.githubusercontent.com/29478700/108627840-a050c200-7468-11eb-8e66-2a5f1cc846ab.png)

**Comment by ic005k** [comment]
Yes, I will optimize it for the next release. Thanks for the feedback.

**Comment by ic005k** [comment]
The plist text display has been optimized, please download the latest version.
