### ISSUE TITLE
小bug报告

### ISSUE THREAD

**Issue by lingering2019** [ic005k/PlistEDPlus#7]
查找替换功能中，对于查找到的项目，无法单个替换，只能是全部替换。另外，也无法选择多项进行编辑如删除。

**Comment by ic005k** [comment]
单个替换，只需在搜索之后，点击跳转到下一个或上一个要替换的内容上面，再点击“替换”即可，如果没有跳转到要替换的某个条目上面，“替换”按钮会是灰色的（没有使能）。

多项删除可以考虑在后面的版本中增加这个功能。

**Comment by lingering2019** [comment]
原来如此。多谢。
