### ISSUE TITLE
[Possible Bug Fix] String type field can contain childs

### ISSUE THREAD

**Issue by dreamwhite** [ic005k/PlistEDPlus#8]
First of all, I'd want to thank you so much for developing this wonderful plist editor.
I just noticed with a friend of mine that actually the editor admits creating a child under a string type field.

Below a screenshot:

![image](https://user-images.githubusercontent.com/17933708/109955159-7908b900-7ce2-11eb-99e1-da726075481f.png)

Opening the same file with other XML editors like XCode or ProperTree doesn't work:

![image](https://user-images.githubusercontent.com/17933708/109955334-a8b7c100-7ce2-11eb-905e-23e384be0fd8.png)

I attach the file I used:

[test.plist.zip](https://github.com/ic005k/PlistEDPlus/files/6083137/test.plist.zip)

Is this intended? As far as I know adding a child under a string type field goes against XML specs.
Please correct me if I'm wrong and thanks again for the great effort

**Comment by ic005k** [comment]
Yes, I will restrict this in the next version to allow only dict and array to exist as subitems. Thanks for the feedback.

**Comment by dreamwhite** [comment]
Also, will you ever consider adding a feature like CorpNewt's ProperTree's OC-Snapshot? 
I don't know what your purpose is with this editor but since .plist files are only used by macOS, it will come in handy at some point for hackintoshing purposes and the OC-Snapshot feature would be a nice touch. I, myself, am using this to edit Opencore's config.plist and I'm always forced to open ProperTree to perform a snapshot and then close it and go back to PlistEDPlus.

**Comment by ic005k** [comment]
> Also, will you ever consider adding a feature like CorpNewt's ProperTree's OC-Snapshot?
> I don't know what your purpose is with this editor but since .plist files are only used by macOS, it will come in handy at some point for hackintoshing purposes and the OC-Snapshot feature would be a nice touch. I, myself, am using this to edit Opencore's config.plist and I'm always forced to open ProperTree to perform a snapshot and then close it and go back to PlistEDPlus.

Oh, I see what you mean. But definitely please try a tool I wrote specifically for OC: https://www.insanelymac.com/forum/topic/344752-open-source-cross-platform-opencore-auxiliary-tools/

And this tool is still being improved and will get better and better, hope you like it or please let me know what you think, thanks.

**Comment by dreamwhite** [comment]
> > Also, will you ever consider adding a feature like CorpNewt's ProperTree's OC-Snapshot?
> > I don't know what your purpose is with this editor but since .plist files are only used by macOS, it will come in handy at some point for hackintoshing purposes and the OC-Snapshot feature would be a nice touch. I, myself, am using this to edit Opencore's config.plist and I'm always forced to open ProperTree to perform a snapshot and then close it and go back to PlistEDPlus.
> 
> Oh, I see what you mean. But definitely please try a tool I wrote specifically for OC: https://www.insanelymac.com/forum/topic/344752-open-source-cross-platform-opencore-auxiliary-tools/
> 
> And this tool is still being improved and will get better and better, hope you like it or please let me know what you think, thanks.

I don't want to discredit your work in any way but I don't like configurators since, as you may imagine, each version of OpenCore introduces new changes like new quirks, new options and so on, and I'm a little bit uncertain that you can guarantee me that the configurator will be updated. Is there any kind of assurance?
I prefer the standard way with ProperTree (just for snapshotting), GenSMBIOS, SSDTTime, MaciASL and PlistEDPlus
Again, thank you so much for your work ^^

**Comment by ic005k** [comment]
> I don't want to discredit your work in any way but I don't like configurators since, as you may imagine, each version of OpenCore introduces new changes like new quirks, new options and so on, and I'm a little bit uncertain that you can guarantee me that the configurator will be updated. Is there any kind of assurance?
> I prefer the standard way with ProperTree (just for snapshotting), GenSMBIOS, SSDTTime, MaciASL and PlistEDPlus
> Again, thank you so much for your work ^^

Oh, totally understand where you're coming from. Anyway, I'll keep improving these apps, including PlistEDPlus, and thanks again for your attention and suggestions. In the meantime, any suggestions or questions are welcome.

**Comment by ic005k** [comment]
> I don't want to discredit your work in any way but I don't like configurators since, as you may imagine, each version of OpenCore introduces new changes like new quirks, new options and so on, and I'm a little bit uncertain that you can guarantee me that the configurator will be updated. Is there any kind of assurance?
> I prefer the standard way with ProperTree (just for snapshotting), GenSMBIOS, SSDTTime, MaciASL and PlistEDPlus
> Again, thank you so much for your work ^^

Oh, totally understand where you're coming from. Anyway, I'll keep improving these apps, including PlistEDPlus, and thanks again for your attention and suggestions. In the meantime, any suggestions or questions are welcome.

**Comment by ic005k** [comment]
> Also, will you ever consider adding a feature like CorpNewt's ProperTree's OC-Snapshot?

New: Add aml, kext, efi files for OpenCore. The operation is very simple, take ACPI as an example: select Add under ACPI, drag and drop one or more aml files to the app window.

Similar features have been added, please download the latest version. This feature should work better than the one you are talking about.

**Comment by dreamwhite** [comment]
> > Also, will you ever consider adding a feature like CorpNewt's ProperTree's OC-Snapshot?
> 
> New: Add aml, kext, efi files for OpenCore. The operation is very simple, take ACPI as an example: select Add under ACPI, drag and drop one or more aml files to the app window.
> 
> Similar features have been added, please download the latest version. This feature should work better than the one you are talking about.

Wonderful! I'll test it asap and report you back if there are any kind of bugs ^^

**Comment by ic005k** [comment]
I am very glad to see your feedback. I will explain the points you mentioned as follows:
1. drag and drop a tab to create a new window (or the first button in the toolbar), and a new window can be formed.
2. The pasting strategy of PlistedPlus is to paste on the previous line of the current line.
3. Regarding the arrangement order of VoodooI2Ckext, this can be optimized later.

In the near future, I will publish a version of optimization for OC, that is, input is automatically completed. For example, if you need to change PickerMode, you only need to input B, and Builtin will appear.

In a word, it will be more and more easy to use. Thank you again for your feedback. I will consider any suggestions comprehensively and constantly improve this APP.

**Comment by dreamwhite** [comment]
> I am very glad to see your feedback. I will explain the points you mentioned as follows:
> 
>     1. drag and drop a tab to create a new window (or the first button in the toolbar), and a new window can be formed.
> 
>     2. The pasting strategy of PlistedPlus is to paste on the previous line of the current line.
> 
>     3. Regarding the arrangement order of VoodooI2Ckext, this can be optimized later.
> 
> 
> In the near future, I will publish a version of optimization for OC, that is, input is automatically completed. For example, if you need to change PickerMode, you only need to input B, and Builtin will appear.
> 
> In a word, it will be more and more easy to use. Thank you again for your feedback. I will consider any suggestions comprehensively and constantly improve this APP.

Wonderful. I'm willing to test eventual betas ^^
